model_params:
  name: 'las_basic'
  log_path: 'log'
  model_path: 'models'
  load_model: 'las_basic'
  load_epochs: 2
  AUF: 40
  HFL: 256
  CS: 128
  VOC: 34
  HFS: 512
  EMB: 64
  lr: 0.0001
  n: 10
  tfr: 0.9