meta_params:
  log_folder: 'log/'
  model_name: 'las_basic'
  model_folder: 'models/'

training_params:
  n_epochs: 20
  learning_rate: 0.0001

model_params:
  name: 'las_basic'
  log_path: 'log'
  model_path: 'models'
  AUF: 40
  HFL: 256
  CS: 128
  VOC: 34
  HFS: 512
  EMB: 64
  lr: 0.0001
  n: 10
  tfr: 0.9