# vanilla model
model_params:
  name: 'las_basic'
  log_path: 'log'
  model_path: 'models'
  load_epochs: 20
  AUF: 40
  HFL: 256
  CS: 128
  VOC: 34
  HFS: 512
  EMB: 64
  lr: 0.001
  n: 30
  tfr: 0.9